{{- $root := . -}}
{{- $globalMetadata := .Values.global.metadata -}}
{{- $globalSharedLabels := $globalMetadata.shared.labels -}}
{{- $globalObjectLabels := $globalMetadata.configMap.labels }}
{{- $globalSharedAnnotations := $globalMetadata.shared.annotations }}
{{- $globalObjectAnnotations := $globalMetadata.configMap.annotations }}
{{- $localMetadata := .Values.receiver.metadata -}}
{{- $localSharedAnnotations := $localMetadata.shared.annotations -}}
{{- $localObjectAnnotations := $localMetadata.configMap.annotations -}}
{{- $localSharedLabels := $localMetadata.shared.labels -}}
{{- $localObjectLabels := $localMetadata.configMap.labels -}}
{{- $localListenerIp := .Values.receiver.specs.network.localListenerIp -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.name }}-{{ $localMetadata.name }}-{{ .Values.collector.specs.volumes.serviceConfig.name }}
  namespace: {{ .Values.collector.metadata.namespace | default .Values.global.namespace }}
  labels: {{ tpl ( toYaml $globalSharedLabels | nindent 4) $ }}
  {{- if $globalObjectLabels }}{{ tpl ( toYaml $globalObjectLabels | nindent 4) . }}{{- end }}
  {{- if $localSharedLabels }}{{ toYaml $localSharedLabels | nindent 4 }}{{- end }}
  {{- if $localObjectLabels }}{{ toYaml $localObjectLabels | nindent 4 }}{{- end }}
  annotations: {{- if $globalSharedAnnotations }}{{ tpl ( toYaml $globalSharedAnnotations | nindent 4) $ }}{{- end}}
  {{- if $globalObjectAnnotations }}{{ tpl ( toYaml $globalObjectAnnotations | nindent 4) . }}{{- end }}
  {{- if $localSharedAnnotations }}{{ toYaml $localSharedAnnotations | nindent 4 }}{{- end }}
  {{- if $localObjectAnnotations }}{{ toYaml $localObjectAnnotations | nindent 4 }}{{- end }}
data:
  {{ .Values.receiver.specs.volumes.serviceConfig.fileName }}: |
    receivers:
      otlp:
        protocols:
    {{- range .Values.receiver.specs.network.ports }}
      {{- if eq .name "grpc"}}
          grpc:
            endpoint: {{ $localListenerIp }}:{{ .internalPort }}
            max_recv_msg_size_mib: 4194304
      {{- end}}
      {{- if eq .name "http"}}
          http:
            endpoint: {{ $localListenerIp }}:{{ .internalPort }}
      {{- end}}
    {{- end}}
    {{- if .Values.receiver.specs.jeager_collector.enable }}
      jaeger:
        protocols:
      {{- range .Values.receiver.specs.network.ports }}
        {{- if eq .name "jaeger-grpc"}}
          grpc:
            endpoint: {{ $localListenerIp }}:{{ .internalPort }}
        {{- end}}
        {{- if eq .name "jaeger-http"}}
          thrift_http:
            endpoint: {{ $localListenerIp }}:{{ .internalPort }}
        {{- end}}
      {{- end}}
    {{- end}}
    {{- if .Values.receiver.specs.zipkin_collector.enable }}
      zipkin:
      {{- range .Values.receiver.specs.network.ports }}
        {{- if eq .name "zipkin"}}
        endpoint: {{ $localListenerIp }}:{{ .internalPort }}
        {{- end}}
      {{- end}}
    {{- end}}
    processors:
      batch:
    exporters:
      loadbalancing:
        protocol:
          otlp:
            timeout: {{ .Values.receiver.specs.configuration.exporters.load_balancing.protocol.otlp.timeout }}
            tls:
              insecure: {{ .Values.receiver.specs.configuration.exporters.load_balancing.protocol.otlp.tls.insecure }}
        resolver:
          dns:
            hostname: {{ .Values.receiver.specs.configuration.exporters.load_balancing.protocol.resolver.dns.hostname }}
            port: {{ .Values.receiver.specs.configuration.exporters.load_balancing.protocol.resolver.dns.port }}

    {{- range .Values.receiver.specs.network.ports }}
      {{- if eq .name "health-check"}}
    extensions:
      health_check:
        endpoint: "{{ $localListenerIp }}:{{ .internalPort }}"
      {{- end }}
    {{- end }}

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers:
            - otlp
    {{- if .Values.receiver.specs.jeager_collector.enable }}
            - jaeger
    {{- end }}
    {{- if .Values.receiver.specs.zipkin_collector.enable }}
            - zipkin
    {{- end }}
          processors: [batch]
          exporters:
            - loadbalancing
