{{- $root := . -}}
{{- $globalMetadata := .Values.global.metadata -}}
{{- $globalSharedLabels := $globalMetadata.shared.labels -}}
{{- $globalObjectLabels := $globalMetadata.configMap.labels }}
{{- $globalSharedAnnotations := $globalMetadata.shared.annotations }}
{{- $globalObjectAnnotations := $globalMetadata.configMap.annotations }}
{{- $localMetadata := .Values.receiver.metadata -}}
{{- $localSharedAnnotations := $localMetadata.shared.annotations -}}
{{- $localObjectAnnotations := $localMetadata.configMap.annotations -}}
{{- $localSharedLabels := $localMetadata.shared.labels -}}
{{- $localObjectLabels := $localMetadata.configMap.labels -}}
{{- $localListenerIp := .Values.receiver.specs.network.localListenerIp -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.name }}-{{ $localMetadata.name }}-{{ .Values.collector.specs.volumes.serviceConfig.name }}
  labels: {{ tpl ( toYaml $globalSharedLabels | nindent 4) $ }}
  {{- if $globalObjectLabels }}{{ tpl ( toYaml $globalObjectLabels | nindent 4) . }}{{- end }}
  {{- if $localSharedLabels }}{{ toYaml $localSharedLabels | nindent 4 }}{{- end }}
  {{- if $localObjectLabels }}{{ toYaml $localObjectLabels | nindent 4 }}{{- end }}
  annotations: {{- if $globalSharedAnnotations }}{{ tpl ( toYaml $globalSharedAnnotations | nindent 4) $ }}{{- end}}
  {{- if $globalObjectAnnotations }}{{ tpl ( toYaml $globalObjectAnnotations | nindent 4) . }}{{- end }}
  {{- if $localSharedAnnotations }}{{ toYaml $localSharedAnnotations | nindent 4 }}{{- end }}
  {{- if $localObjectAnnotations }}{{ toYaml $localObjectAnnotations | nindent 4 }}{{- end }}
data:
  {{ .Values.receiver.specs.volumes.serviceConfig.fileName }}: |
    receivers:
      otlp:
        protocols:
          {{- include "reciver.protocols" (dict "service" "grpc" "protocols" .Values.global.collector_services "localListenerIp" .Values.receiver.specs.network.localListenerIp ) | nindent 10 }}
          {{- include "reciver.protocols" (dict "service" "http" "protocols" .Values.global.collector_services "localListenerIp" .Values.receiver.specs.network.localListenerIp ) | nindent 10 }}
      {{- include "reciver.protocols" (dict "service" "zipkin" "protocols" .Values.global.collector_services "localListenerIp" .Values.receiver.specs.network.localListenerIp ) | nindent 6 }}
      jaeger:
        protocols:
          {{- include "reciver.protocols" (dict "service" "jaeger-grpc" "protocols" .Values.global.collector_services "localListenerIp" .Values.receiver.specs.network.localListenerIp ) | nindent 10 }}
          {{- include "reciver.protocols" (dict "service" "jaeger-http" "protocols" .Values.global.collector_services "localListenerIp" .Values.receiver.specs.network.localListenerIp ) | nindent 10 }}

    processors:
      batch:
    exporters:
      {{- include "reciver.exporters" (dict "Values" .Values) | indent 4 }}

    extensions:
    {{- include "receiver.configMap.extentions" (dict "service" "health_check" "protocols" .Values.global.collector_services "localListenerIp" .Values.receiver.specs.network.localListenerIp ) | indent 2 }}
    {{- include "receiver.configMap.extentions" (dict "service" "zpages" "protocols" .Values.global.collector_services "localListenerIp" .Values.receiver.specs.network.localListenerIp ) | indent 2 }}

    service:
        {{- include "reciver.configMap.services.telemetry" (dict "protocols" .Values.global.collector_services "service" "metrics" "localListenerIp" .Values.receiver.specs.network.localListenerIp ) | indent 6}}
      extensions:
        {{- include "reciver.services" (dict "protocols" .Values.global.collector_services "service" "health_check") | indent 2 }}
        {{- include "reciver.services" (dict "protocols" .Values.global.collector_services "service" "zpages") | indent 2 }}

      pipelines:
        traces:
          receivers:
            - otlp
            {{- include "reciver.services" (dict "protocols" .Values.global.collector_services "service" "zipkin") | indent 8 }}
            {{- if (include "reciver.services.jaeger" (dict "protocols" .Values.global.collector_services) ) }}
            - jaeger
            {{- end }}
          processors:
            - batch
          exporters:
            - loadbalancing


