{{- $root := . -}}
{{- $globalMetadata := .Values.global.metadata -}}
{{- $globalSharedLabels := $globalMetadata.shared.labels -}}
{{- $globalObjectLabels := $globalMetadata.destinationRule.labels }}
{{- $globalSharedAnnotations := $globalMetadata.shared.annotations }}
{{- $globalObjectAnnotations := $globalMetadata.destinationRule.annotations }}
{{- $localMetadata := .Values.receiver.metadata -}}
{{- $localSharedAnnotations := $localMetadata.shared.annotations -}}
{{- $localObjectAnnotations := $localMetadata.destinationRule.annotations -}}
{{- $localSharedLabels := $localMetadata.shared.labels -}}
{{- $localObjectLabels := $localMetadata.destinationRule.labels -}}
{{- $version := tpl ( toString $globalSharedLabels.receiverVersion ) . }}
{{- if .Values.receiver.specs.network.istio.enabled }}
{{- $host := .Values.receiver.specs.network.istio.defaultHostHeader -}}
{{ $desinationRuleName := printf "%s-%s-%s-detinationRule" .Values.global.name $localMetadata.name .Values.receiver.specs.service.name | lower }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ $desinationRuleName }}
  labels: {{ tpl ( toYaml $globalSharedLabels | nindent 4) $ }}
  {{- if $globalObjectLabels }}{{ tpl ( toYaml $globalObjectLabels | nindent 4) . }}{{- end }}
  {{- if $localSharedLabels }}{{ toYaml $localSharedLabels | nindent 4 }}{{- end }}
  {{- if $localObjectLabels }}{{ toYaml $localObjectLabels | nindent 4 }}{{- end }}
  annotations: {{- if $globalSharedAnnotations }}{{ tpl ( toYaml $globalSharedAnnotations | nindent 4) $ }}{{- end}}
  {{- if $globalObjectAnnotations }}{{ tpl ( toYaml $globalObjectAnnotations | nindent 4) . }}{{- end }}
  {{- if $localSharedAnnotations }}{{ toYaml $localSharedAnnotations | nindent 4 }}{{- end }}
  {{- if $localObjectAnnotations }}{{ toYaml $localObjectAnnotations | nindent 4 }}{{- end }}
spec:
  host: {{ .Values.receiver.specs.network.istio.defaultHostHeader }}
  trafficPolicy:
    portLevelSettings:
      {{- range .Values.global.collector_services }}
      - port:
          number: {{ .internalPort }}{{ toYaml $root.Values.receiver.specs.network.istio.ruleTrafficPolicy | nindent 8 }}
      {{- end }}
  subsets:
    - name: {{ .Values.receiver.specs.network.istio.subnetName }}
      labels:
        app: {{ $globalSharedLabels.app }}
        receiverVersion: {{ $version }}
      trafficPolicy: {{ toYaml .Values.receiver.specs.network.istio.subnetTrafficPolicy | nindent 8 }}
{{- end }}