{{- $root := . -}}
{{- $globalMetadata := .Values.global.metadata -}}
{{- $globalSharedLabels := $globalMetadata.shared.labels -}}
{{- $globalObjectLabels := $globalMetadata.virtualService.labels }}
{{- $globalSharedAnnotations := $globalMetadata.shared.annotations }}
{{- $globalObjectAnnotations := $globalMetadata.virtualService.annotations }}
{{- $localMetadata := .Values.receiver.metadata -}}
{{- $localSharedAnnotations := $localMetadata.shared.annotations -}}
{{- $localObjectAnnotations := $localMetadata.virtualService.annotations -}}
{{- $localSharedLabels := $localMetadata.shared.labels -}}
{{- $localObjectLabels := $localMetadata.virtualService.labels -}}
{{- $istio := .Values.receiver.specs.network.istio }}
{{- $detinationRule := $istio.destinationRuleName }}
{{- if .Values.receiver.specs.network.istio.enabled }}
{{- range .Values.receiver.specs.network.istio.rules }}
{{- $rule := . }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $root.Values.global.name }}-{{ $localMetadata.name }}-{{ .name }}-vsvc
  labels: {{ tpl ( toYaml $globalSharedLabels | nindent 4) $ }}
  {{- if $globalObjectLabels }}{{ tpl ( toYaml $globalObjectLabels | nindent 4) . }}{{- end }}
  {{- if $localSharedLabels }}{{ toYaml $localSharedLabels | nindent 4 }}{{- end }}
  {{- if $localObjectLabels }}{{ toYaml $localObjectLabels | nindent 4 }}{{- end }}
  annotations: {{- if $globalSharedAnnotations }}{{ tpl ( toYaml $globalSharedAnnotations | nindent 4) $ }}{{- end }}
  {{- if $globalObjectAnnotations }}{{ tpl ( toYaml $globalObjectAnnotations | nindent 4) . }}{{- end }}
  {{- if $localSharedAnnotations }}{{ toYaml $localSharedAnnotations | nindent 4 }}{{- end }}
  {{- if $localObjectAnnotations }}{{ toYaml $localObjectAnnotations | nindent 4 }}{{- end }}
spec:
  hosts:
    - {{ $rule.hostHeader | default $istio.defaultHostHeader }}
  gateways:
    - {{ $root.Values.global.name }}-{{ $localMetadata.name }}-gateway
  http:
  {{- range .ingress }}
    - match:
      - uri:
          prefix: {{ .uriPrefix }}
      route:
      - destination:
          host: {{ $rule.hostHeader | default $istio.defaultHostHeader }}
          subset: {{ $istio.subnetName }}
  {{- end }}
{{- end }}
---
{{- end }}