{{- $root := . -}}
{{- $globalMetadata := .Values.global.metadata -}}
{{- $globalSharedLabels := $globalMetadata.shared.labels -}}
{{- $globalObjectLabels := $globalMetadata.destinationRule.labels }}
{{- $globalSharedAnnotations := $globalMetadata.shared.annotations }}
{{- $globalObjectAnnotations := $globalMetadata.destinationRule.annotations }}
{{- $localMetadata := .Values.collector.metadata -}}
{{- $localSharedAnnotations := $localMetadata.shared.annotations -}}
{{- $localObjectAnnotations := $localMetadata.destinationRule.annotations -}}
{{- $localSharedLabels := $localMetadata.shared.labels -}}
{{- $localObjectLabels := $localMetadata.destinationRule.labels -}}
{{- $version := tpl ( toString $globalSharedLabels.collectorVersion ) . }}
{{- if .Values.collector.specs.network.istio.enabled }}
{{- $host := .Values.collector.specs.network.istio.defaultHostHeader -}}
{{- range .Values.collector.specs.services }}
{{ $desinationRuleName := printf "%s-%s-%s-detinationRule" $root.Values.global.name $localMetadata.name .name | lower }}
{{ $rule := . }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ $desinationRuleName }}
  labels: {{ tpl ( toYaml $globalSharedLabels | nindent 4) $ }}
  {{- if $globalObjectLabels }}{{ tpl ( toYaml $globalObjectLabels | nindent 4) . }}{{- end }}
  {{- if $localSharedLabels }}{{ toYaml $localSharedLabels | nindent 4 }}{{- end }}
  {{- if $localObjectLabels }}{{ toYaml $localObjectLabels | nindent 4 }}{{- end }}
  annotations: {{- if $globalSharedAnnotations }}{{ tpl ( toYaml $globalSharedAnnotations | nindent 4) $ }}{{- end}}
  {{- if $globalObjectAnnotations }}{{ tpl ( toYaml $globalObjectAnnotations | nindent 4) . }}{{- end }}
  {{- if $localSharedAnnotations }}{{ toYaml $localSharedAnnotations | nindent 4 }}{{- end }}
  {{- if $localObjectAnnotations }}{{ toYaml $localObjectAnnotations | nindent 4 }}{{- end }}
spec:
  host: {{ $root.Values.receiver.specs.network.istio.defaultHostHeader }}
  trafficPolicy:
    portLevelSettings:
      {{- range .ports }}
      - port:
          number: {{ .internalPort }}
        {{- if eq $rule.serviceType "LoadBalancer" }}
        loadBalancer:
          simple: {{ .loadBalancer.simple | default $rule.loadBalancer.simple }}
        {{- end }}
      {{- end }}
  subsets:
    - name: {{ $root.Values.collector.specs.network.istio.subnetName }}
      labels:
        app: {{ $globalSharedLabels.app }}
        collectorVersion: {{ $version }}
      trafficPolicy: {{ toYaml $root.Values.collector.specs.network.istio.trafficPolicy | nindent 8 }}
  {{- end }}
  {{- end }}