{{- $root := . -}}
{{- $globalMetadata := .Values.global.metadata -}}
{{- $globalSharedLabels := $globalMetadata.shared.labels -}}
{{- $globalObjectLabels := $globalMetadata.service.labels }}
{{- $globalSharedAnnotations := $globalMetadata.shared.annotations }}
{{- $globalObjectAnnotations := $globalMetadata.service.annotations }}
{{- $localMetadata := .Values.collector.metadata -}}
{{- $localSharedAnnotations := $localMetadata.shared.annotations -}}
{{- $localObjectAnnotations := $localMetadata.service.annotations -}}
{{- $localSharedLabels := $localMetadata.shared.labels -}}
{{- $localObjectLabels := $localMetadata.service.labels -}}
{{- $localListenerIp := .Values.collector.specs.network.localListenerIp -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.name }}-{{ $localMetadata.name }}-{{ .Values.collector.specs.service.name }}-service
  labels: {{ tpl ( toYaml $globalSharedLabels | nindent 4) $ }}
  {{- if $globalObjectLabels }}{{ tpl ( toYaml $globalObjectLabels | nindent 4) . }}{{- end }}
  {{- if $localSharedLabels }}{{ toYaml $localSharedLabels | nindent 4 }}{{- end }}
  {{- if $localObjectLabels }}{{ toYaml $localObjectLabels | nindent 4 }}{{- end }}
  annotations: {{- if $globalSharedAnnotations }}{{ tpl ( toYaml $globalSharedAnnotations | nindent 4) $ }}{{- end}}
  {{- if $globalObjectAnnotations }}{{ tpl ( toYaml $globalObjectAnnotations | nindent 4) . }}{{- end }}
  {{- if $localSharedAnnotations }}{{ toYaml $localSharedAnnotations | nindent 4 }}{{- end }}
  {{- if $localObjectAnnotations }}{{ toYaml $localObjectAnnotations | nindent 4 }}{{- end }}
spec:
  type: {{ .Values.collector.specs.service.serviceType }}
  {{- if eq .Values.collector.specs.service.serviceType "ClusterIP" }}
  clusterIP: None
  {{- end }}
  ports:
  {{- range .Values.global.collector_services }}
  {{- if eq .enabled true }}
    - port: {{ .externalPort }}
      targetPort: {{ .internalPort }}
      protocol: {{ .protocol }}
      name: {{ .name | replace "_" "-" }}
      {{- if $root.Values.collector.specs.service.ports.extraConfigPerPort }}
      {{- toYaml $root.Values.collector.specs.service.ports.extraConfigPerPort | nindent 6 }}
      {{- end}}
    {{- end  }}
  {{- end }}
  selector:
    {{- toYaml .Values.collector.specs.service.selector | nindent 4}}