{{- $root := . -}}
{{- $globalMetadata := .Values.global.metadata -}}
{{- $globalSharedLabels := $globalMetadata.shared.labels -}}
{{- $globalObjectLabels := $globalMetadata.configMap.labels }}
{{- $globalSharedAnnotations := $globalMetadata.shared.annotations }}
{{- $globalObjectAnnotations := $globalMetadata.configMap.annotations }}
{{- $localMetadata := .Values.load_balancer.metadata -}}
{{- $localSharedAnnotations := $localMetadata.shared.annotations -}}
{{- $localObjectAnnotations := $localMetadata.configMap.annotations -}}
{{- $localSharedLabels := $localMetadata.shared.labels -}}
{{- $localObjectLabels := $localMetadata.configMap.labels -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.name }}-{{ $localMetadata.name }}-{{ .Values.sampling_collector.specs.volumes.serviceConfig.name }}
  namespace: {{ .Values.sampling_collector.metadata.namespace | default .Values.global.namespace }}
  labels: {{ tpl ( toYaml $globalSharedLabels | nindent 4) $ }}
{{- if $globalObjectLabels }}{{ tpl ( toYaml $globalObjectLabels | nindent 4) . }}{{- end }}
{{- if $localObjectLabels }}{{ toYaml $localObjectLabels | nindent 4 }}{{- end }}
{{- if $localObjectLabels }}{{ toYaml $localObjectLabels | nindent 4 }}{{- end }}
  annotations: {{ tpl ( toYaml $globalSharedAnnotations | nindent 4) $ }}
{{- if $globalObjectAnnotations }}{{ tpl ( toYaml $globalObjectAnnotations | nindent 4) . }}{{- end }}
{{- if $localSharedAnnotations }}{{ toYaml $localSharedAnnotations | nindent 4 }}{{- end }}
{{- if $localObjectAnnotations }}{{ toYaml $localObjectAnnotations | nindent 4 }}{{- end }}
data:
  {{ .Values.load_balancer.specs.volumes.serviceConfig.fileName }}: |
    receivers:
      otlp:
        protocols:
    {{- range .Values.load_balancer.specs.network.ports }}
    {{- if eq .name "grpc"}}
          grpc:
            endpoint: {{ $root.Values.load_balancer.specs.network.localListenerIp }}:{{ .internalPort }}
    {{- end}}
    {{- if eq .name "http"}}
          http:
            endpoint: {{ $root.Values.load_balancer.specs.network.localListenerIp }}:{{ .internalPort }}
    {{- end}}
    {{- end}}

    exporters:
      loadbalancing:
        protocol:
          otlp:
            timeout: {{ .Values.load_balancer.specs.configuration.exporters.load_balancing.protocol.otlp.timeout }}
            tls:
              insecure: {{ .Values.load_balancer.specs.configuration.exporters.load_balancing.protocol.otlp.tls.insecure }}
        resolver:
          dns:
            {{- with ( first .Values.sampling_collector.specs.services ) }}
            {{- if eq .serviceType "ClusterIP" }}
            hostname: {{ $root.Values.global.name }}-{{ $root.Values.sampling_collector.metadata.name }}-{{ .name }}-service
            {{ else }}
            hostname: {{ required "Missing configuration of load_balancer.specs.configuration.exporters.load_balancing.protocol.resolver.dns.hostname" $root.Values.load_balancer.specs.configuration.exporters.load_balancing.protocol.resolver.dns.hostname }}
            {{- end }}
            {{- end }}
            port: {{ .Values.load_balancer.specs.configuration.exporters.load_balancing.protocol.resolver.dns.port }}

    {{- range .Values.load_balancer.specs.network.ports }}
    {{- if eq .name "health-check"}}
    extensions:
      health_check:
        endpoint: "{{ $root.Values.load_balancer.specs.network.localListenerIp }}:{{ .internalPort }}"
    {{- end}}
    {{- end}}

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers:
            - otlp
          processors: []
          exporters: [loadbalancing]
