{{- $root := . -}}
{{- $globalMetadata := .Values.global.metadata -}}
{{- $globalSharedLabels := $globalMetadata.shared.labels -}}
{{- $globalObjectLabels := $globalMetadata.destinationRule.labels }}
{{- $globalSharedAnnotations := $globalMetadata.shared.annotations }}
{{- $globalObjectAnnotations := $globalMetadata.destinationRule.annotations }}
{{- $localMetadata := .Values.load_balancer.metadata -}}
{{- $localSharedAnnotations := $localMetadata.shared.annotations -}}
{{- $localObjectAnnotations := $localMetadata.destinationRule.annotations -}}
{{- $localSharedLabels := $localMetadata.shared.labels -}}
{{- $localObjectLabels := $localMetadata.destinationRule.labels -}}
{{- if .Values.load_balancer.specs.network.istio.enabled }}
{{- range .Values.load_balancer.specs.services }}
{{- if eq .serviceType "LoadBalancer" }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ $root.Values.global.name }}-{{ $localMetadata.name }}-{{ .name }}-balancer
  labels: {{ tpl ( toYaml $globalSharedLabels | nindent 4) $ }}
{{- if $globalObjectLabels }}{{ tpl ( toYaml $globalObjectLabels | nindent 4) . }}{{- end }}
{{- if $localObjectLabels }}{{ toYaml $localObjectLabels | nindent 4 }}{{- end }}
{{- if $localObjectLabels }}{{ toYaml $localObjectLabels | nindent 4 }}{{- end }}
  annotations: {{ tpl ( toYaml $globalSharedAnnotations | nindent 4) $ }}
{{- if $globalObjectAnnotations }}{{ tpl ( toYaml $globalObjectAnnotations | nindent 4) . }}{{- end }}
{{- if $localSharedAnnotations }}{{ toYaml $localSharedAnnotations | nindent 4 }}{{- end }}
{{- if $localObjectAnnotations }}{{ toYaml $localObjectAnnotations | nindent 4 }}{{- end }}
spec:
  host: {{ .name }}
  trafficPolicy:
    portLevelSettings:
    {{- range .ports }}
    - port:
        number: {{ .internalPort }}
      loadBalancer:
        simple: {{ .loadBalancer.simple }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}